<a href="https://colab.research.google.com/github/arbeecvam/Linear-Algebra-2nd-Sem/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE

Alera, Arbee Chrystel and 
Aquilon, Althea Francesca

## Laboratory 2: Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions. 

### Objectives

At the end of this activity you will be able to:

1. Be familiar with matrices and their relation to linear equations. 
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## **Matrices**

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        4x + 29y \\ 
        10x - 17y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        3x+2y+6z \\ 
        3x -2y -z \\
        -9x + 3y +8z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        x+y+2z \\ 
        4x -2y -z \\
        -2x + 9y +2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equatins with 2 parameters. While $B$ is a system of 3 expations with 3 parameters We car present them as matrices as:

$$
A=\begin{bmatrix} 4 & 29 \\ 10 & {-17}\end{bmatrix} \\
B=\begin{bmatrix} 3 & 2 & 6 \\ 3 & -2 & -1 \\ -9 & 3 & 8\end{bmatrix} \\
C=\begin{bmatrix} 1 & 1 & 2 \\ 4 & -2 & -1 \\ -2 & 9 & 2\end{bmatrix}
$$


So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

## **Declaring Matrices**

The system of linear equations is represented as a matrix in which the entities or numbers present in matrices are referred to as the elements of a matrix. These elements are then arranged and ordered in rows and columns which makes up the array-like structure of the matrices. 

The number of rows is denoted by i, while the number of columns is denoted by j. Therefore, the ***size of the matrix is represented by iхj***, shown in the figure below.


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In **declaring matrices**, defining a function must be done to make it possible for the code to print the matrix, together with its shape and rank.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function. 
def describe_mat (matrix): 
     print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [1, 1, 2],
    [3, 1, 4]
])
describe_mat(G)

Matrix:
[[1 1 2]
 [3 1 4]]

Shape:	(2, 3)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix

B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat (B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H= np.array([1,2,3,4,5]) 
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## **Categorizing Matrices**

There are several ways of classifying matrices. They can be categorized ***according to their shape and elemental values***. 

## **According to Shape**

### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be spaces of a bigger vector $i \times $j and column matrices would be $i \times 1$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D=np.array([ 
    7, 3, 6, -4
]) # this is a 1-D Matrix with a shape of (3,the ), it's not really considered as a row matrix. 
row_mat_2D = np.array([
    [900,8,3,-2]
]) ## this is a 2-D Matrix with a shape of (1,3) 

describe_mat(row_mat_1D)
describe_mat (row_mat_2D)

Matrix:
[ 7  3  6 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[900   8   3  -2]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [4],
    [9],
    [7]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[4]
 [9]
 [7]]

Shape:	(3, 1)
Rank:	2



### Square Matrices

Square matrices are ***matrices that have an equal number of rows and columns***— it can be denoted as i = j, for that reason, the number of elements in it is always a perfect square number.

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] ==matrix.shape [1] else False 
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([ 
    [6,1000,8],
    [23,4,5], 
    [1,2,3]
])
non_square_mat = np.array([
     [9,8,1000000000],
     [327638196,182781728,872837]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[   6 1000    8]
 [  23    4    5]
 [   1    2    3]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[         9          8 1000000000]
 [ 327638196  182781728     872837]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## **According to Element Values**

### Null Matrix

A Null matrix is a ***matrix that has no elements, not even one or zero***. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
     is_square = True if matrix.shape[0] == matrix.shape[1] else False 
     print(f'Matrix: \n{matrix}\n\nshape:\t{matrix. shape}\nRank:\t{matrix.ndim}\nIs Square: (is_square)\n') 
  else:
    print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


### Zero Matrix

A zero matrix is any rectangular matrix in which ***all its elements in the matrix are zero.***


In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')



Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but ***all of its elements are 1s instead of 0s***.

In [ ]:
ones_mat_row = np.ones ((1,2))
ones_mat_sqr = np.ones((2, 2))
ones_mat_rct = np.ones((3,2))

print(f'ones Row Matrix: \n{ones_mat_row}') 
print(f'ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


ones Row Matrix: 
[[1. 1.]]
ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

A Diagonal Matrix is a square matrix wherein ***all its non-diagonal elements are zeros.***

In [ ]:
np.array([
    [2, 0, 0],
    [0, 8, 0],
    [0, 0, 4]
])
# a[1,1], a[2,2], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 8, 0],
       [0, 0, 4]])

In [ ]:
d = np.diag ([7,5,2,3])
d

array([[7, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [ ]:
d.shape[0] == d.shape[1]

True

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the ***values at the diagonal are ones (1)***. 

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that ***has values above the diagonal.***

In [ ]:
np.array([
  [5,9,8],
  [0,283,9],
  [0,0,1],
  [0,0,0]
])

array([[  5,   9,   8],
       [  0, 283,   9],
       [  0,   0,   1],
       [  0,   0,   0]])

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that ***has values below the diagonal.***

In [ ]:
np.array([
  [0,0,0],
  [283,0,0],
  [910,8,0],
  [2,93,8]      
])

array([[  0,   0,   0],
       [283,   0,   0],
       [910,   8,   0],
       [  2,  93,   8]])

## **Matrix Algebra**

### Addition

In [ ]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
  [2,2],
  [0,0],
  [5,7]
])
A+B

array([[3, 4],
       [2, 3],
       [9, 8]])

In [ ]:
2+A ##Broadcasting
#2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

### Subtraction

In [ ]:
A-B

array([[-1,  0],
       [ 2,  3],
       [-1, -6]])

In [ ]:
3-B

array([[ 1,  1],
       [ 3,  3],
       [-2, -4]])

### Element-wise Multiplication

Element-Wise Multiplication in Python can be utilized using two methods,  ***the np.multiply() operator and the * operator.***

In [ ]:
A*B
np.multiply(A,B)

array([[ 2,  4],
       [ 0,  0],
       [20,  7]])

In [ ]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [ ]:
##A@B

In [ ]:
alpha = 10** - 10
A/(alpha+B)

array([[0.4       , 0.4       , 0.4       ],
       [0.5       , 0.5       , 0.5       ],
       [0.57142857, 0.57142857, 0.57142857]])

In [ ]:
np.add(A,B)

array([[ 7, 14, 21],
       [ 9, 18, 27],
       [11, 22, 33]])

# **PRACTICE**

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$

In [ ]:
theta = np.array([
  [5,3,-1]
])
describe_mat(theta)

Matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2
Is Square: False



2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [ ]:
A = np.array([
  [1,2,1],
  [0,4,-1],
  [10,0,0]
])
describe_mat(A)
    

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [10  0  0]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
G = \left\{\begin{array}
1x + 7y +8z\\
2x + 2y + 2z\\
4x + 6y + 7z
\end{array}\right.
$$



4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \left\{\begin{array}
1x \\
2x + 2y \\
4x + 6y + 7z
\end{array}\right.
$$
 

$$ H=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}
$$

#**ACTIVITY**

### **Task 1**

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np

In [ ]:
def mat_desc(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print (f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [ ]:
mat_A= np.ones((6,6,))

print('Matrix A:')
mat_desc(mat_A)

output = np.all((np.identity(6)))
if output:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

output = np.all((mat_A == 1))
if output:
  print('Ones Matrix')
else:
  print('Not a Ones Matrix')

output = np.all((mat_A == 0))
if output:
  print('Zero Matrix')
else:
  print('Non-zero Matrix')

Matrix A:
Matrix:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Shape:	(6, 6)
Rank:	2
Is Square: True

Not an Identity Matrix
Ones Matrix
Non-zero Matrix


In [ ]:
mat_B= np.ones((8,4,))
print('Matrix B:')
mat_desc(mat_B)

output = np.all((np.identity(8)))
if output:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

output = np.all((mat_B == 2))
if output:
  print('Ones Matrix')
else:
  print('Not a Ones Matrix')

output = np.all((mat_B == 0))
if output:
  print('Zero Matrix')
else:
  print('Non-Zero Matrix')

Matrix B:
Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Shape:	(8, 4)
Rank:	2
Is Square: False

Not an Identity Matrix
Not a Ones Matrix
Non-Zero Matrix


In [ ]:
mat_C= np.ones((6,3,))
print('Matrix C:')
mat_desc(mat_C)

output = np.all((np.identity(1)))
if output:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

output = np.all((mat_C == 0))
if output:
  print('Ones Matrix')
else:
  print('Not a Ones Matrix')

output = np.all((mat_C == 0))
if output:
  print('Zero Matrix')
else:
  print('Non-Zero Matrix')

Matrix C:
Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Shape:	(6, 3)
Rank:	2
Is Square: False

Identity Matrix
Not a Ones Matrix
Non-Zero Matrix


# Task **2**

::Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the difference of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
A = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

B = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matrix_A = np.shape(A)
matrix_B = np.shape(B)

def mat_operations(A,B):
  matrix_A = np.shape(A)
  matrix_B = np.shape(B)

if matrix_A == matrix_B:
  print("The sum is: ")
  print(A+B)
  print("The difference is: ")
  print(A-B)
  print("The product is: ")
  print(A*B)
  print("The quotient is: ")
  print(A/B)
else:
  print("The matrices are not viable for operation")

The sum is: 
[[10 10 10]
 [10 10 10]
 [10 10 10]]
The difference is: 
[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]
The product is: 
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
The quotient is: 
[[9.         4.         2.33333333]
 [1.5        1.         0.66666667]
 [0.42857143 0.25       0.11111111]]


In [ ]:
H = np.array([
    [5,5,0],
    [1,7,3],
    [4,2,9]
])

I = np.array([
    [1,2,3,0],
    [4,51,0,7],
    [7,6,9,10]
])

matrix_H = np.shape(H)
matrix_I = np.shape(I)

def mat_operations(H,I):
  matrix_A = np.shape(H)
  matrix_B = np.shape(I)

if matrix_H == matrix_I:
  print("The sum is: ")
  print(H+I)
  print("The difference is: ")
  print(H-I)
  print("The product is: ")
  print(H*I)
  print("The quotient is: ")
  print(H/I)
else:
  print("The matrices are not viable for operation")


The matrices are not viable for operation


In [ ]:
Alera = np.array([
    [1,3,6],
    [10,15,21],
    [28,36,45]
])

Aquilon = np.array([
    [1,1,1],
    [3,3,3],
    [7,7,7]
])

matrix_Alera = np.shape(Alera)
matrix_Aquilon = np.shape(Aquilon)

def mat_operations(Alera,Aquilon):
  matrix_Alera = np.shape(Alera)
  matrix_Aquilon = np.shape(Aquilon)

if matrix_Alera == matrix_Aquilon:
  print("The sum is: ")
  print(Aquilon+Alera)
  print("The difference is: ")
  print(Aquilon-Alera)
  print("The product is: ")
  print(Aquilon*Alera)
  print("The quotient is: ")
  print(Aquilon/Alera)
else:
  print("The matrices are not viable for operation")

The sum is: 
[[ 2  4  7]
 [13 18 24]
 [35 43 52]]
The difference is: 
[[  0  -2  -5]
 [ -7 -12 -18]
 [-21 -29 -38]]
The product is: 
[[  1   3   6]
 [ 30  45  63]
 [196 252 315]]
The quotient is: 
[[1.         0.33333333 0.16666667]
 [0.3        0.2        0.14285714]
 [0.25       0.19444444 0.15555556]]


## Conclusion 


The learners have gained enough knowledge and skills in utilizing matrices in this laboratory. Beginning with translating linear equations into matrices, declaring and describing different sizes of matrices, categorizing matrices according to their shapes and elemental values, and lastly performing algebraic operations with the matrices. Moreover, the extra activity given was also a great opportunity to hasten their capabilities in programming. Lastly, they have realized the importance of matrices when it comes to technology because of its advantage of ***giving quick but good approximations to complicated problems***. Aside from these, it has a lot of application in several fields, making it essential for the improvement of our society. 
